#!/bin/sh

[ -z $CXX ] && CXX=g++
[ -z $ECHO ] && ECHO=/bin/echo

MACOSX_DEPLOYMENT_TARGET=10.5
export MACOSX_DEPLOYMENT_TARGET

LIBS=""
LOGG_LIBS="/usr/local/universal/lib/libogg.a /usr/local/universal/lib/libvorbis.a /usr/local/universal/lib/libvorbisenc.a"
STATIC=1
CHECK_FLTK=1
CHECK_QT=0
CHECK_LIBLAME=1
CHECK_LIBVORBIS=1
CHECK_LIBOPUS=1
OGG=0
prefix=/usr/local

header_flags=-I/opt/local/include
lib_flags=-L/usr/local/universal/lib
pa_header=$header_flags
pa_lib=$lib_flags
vorbis_header=$header_flags
vorbis_lib=$lib_flags
lame_header=$header_flags
lame_lib=$lib_flags

##############################################################

msg_chkfor() {
    ${ECHO} -n "checking for "$1" ... "
}

check_docs() {
    
    msg_chkfor "asciidoc"
    if which asciidoc 1> /dev/null 2>&3
    then
        ${ECHO} "OK"
        ${ECHO} "#_______________________" >&4
        ${ECHO} "WITH_DOCS=1" >&4
        ${ECHO} "" >&4
    else
        ${ECHO} "no. you cant rebuild the docs."
    fi
}

check_tools() {

    msg_chkfor "c++ compiler"
    if which $CXX 1> /dev/null 2>&3
    then
        ${ECHO} "OK"
        ${ECHO} "---------------------------------" 1>&3
        $CXX -v 1>&3 2>&3
        ${ECHO} "---------------------------------" 1>&3
    else
        ${ECHO} "FAILED"
        ${ECHO} "error, no compiler found"
        exit 1
    fi
}

check_portaudio() {
    cat << EOF >tmp.c
#include <portaudio.h>
int main() {
PaError p_err = Pa_Initialize();
Pa_Terminate();
return 0;
}
EOF
    msg_chkfor "compile with PortAudio"
    if ${CXX} $pa_header -c tmp.c -o tmp 2>&3
    then
        ${ECHO} "OK"
        msg_chkfor "link with PortAudio"
        if ${CXX} $pa_header $pa_lib tmp.c -o tmp -lportaudio 2>&3
        then
            ${ECHO} "OK"
            ${ECHO} "#_______________________" >&4
                [ "$STATIC" -eq 0 ] && ${ECHO} "LIBS+= -lportaudio" >&4
                ${ECHO} "" >&4
                ${ECHO} "CXXFLAGS+=$pa_header" >&4
                ${ECHO} "LDFLAGS+=$pa_lib" >&4
            else
                ${ECHO} "FAILED"
                ${ECHO} "ABORT: butt requires PortAudio v19"
                ${ECHO} ""
                exit 1
            fi
        else
            ${ECHO} "FAILED"
            ${ECHO} "ABORT: butt requires PortAudio v19"
            ${ECHO} ""
            exit 1
        fi

}


check_fltk() {


cat << EOF >tmp.c
#include <FL/Fl_Double_Window.H>

int main() {
Fl_Double_Window *win = new Fl_Double_Window(0,0);
delete win;
return 0;
}
EOF

cat << EOF >tmp2.c
#include <FL/Fl_Button.H>

int main() {
Fl_Button* btn = new Fl_Button(0, 0, 0, 0);
btn->box(FL_GTK_UP_BOX);

delete btn;
return 0;
}
EOF

msg_chkfor "fltk-config"
if which fltk-config 1> /dev/null 2>&3
then
    ${ECHO} "OK"
    msg_chkfor "compile with fltk"
    if ${CXX} -c tmp.c -o tmp `fltk-config --cxxflags` 2>&3
    then
        ${ECHO} "OK"
        msg_chkfor "fltk has FL_GTK_UP_BOX"
        if ${CXX} -c tmp2.c -o tmp `fltk-config --cxxflags` 2>&3
        then
            ${ECHO} "OK"
            msg_chkfor "link with fltk"
            if ${CXX} tmp.c -o tmp `fltk-config --cxxflags` `fltk-config --ldflags` 2>&3
            then
                ${ECHO} "OK"
                ${ECHO} "#_______________________" >&4
                ${ECHO} "WITH_FLTK:=1" >&4
                ${ECHO} "CXXFLAGS_FLTK:=`fltk-config --cxxflags` -DFLTK1" >&4
                ${ECHO} "LIBS_FLTK:=/usr/local/universal/lib/libfltk.a -framework Carbon -framework ApplicationServices" >&4
                ${ECHO} "SRC_FLTK:=FLTK/fl_callbacks.cpp FLTK/fl_funcs.cpp FLTK/flgui.cpp FLTK/Fl_ILM216.cpp FLTK/Fl_Native_File_Chooser.cpp" >&4
                ${ECHO} "" >&4
                GUI=FLTK
            else
                ${ECHO} "FAILED"
                ${ECHO} "can't link against fltk. See config.log for more details"
                rm config.mk
                exit 1
            fi
        else
            ${ECHO} "FAILED"
            ${ECHO} "You need at least fltk version 1.1.8"
            exit 1
        fi
    else
        ${ECHO} "FAILED"
        ${ECHO} "can'compile with fltk. See config.log for more details"
        rm config.mk
        exit 1
    fi

else
    ${ECHO} "FAILED"
    ${ECHO} "fltk-config was not found on your PC"
    rm config.mk
    exit 1
fi

}

check_qt() {

    ${ECHO} "WITH_QT:=1" >&4
    ${ECHO} "SRC_QT:=QT/qt_funcs.cpp" >&4
    GUI=QT

}

check_libmp3lame() {

    cat << EOF >tmp.c
#include <lame/lame.h>
int main() {

lame_global_flags *gfp;
gfp = lame_init();
lame_close(gfp);

return 0;
}
EOF
    msg_chkfor "compile with libmp3lame (lame)"
    if ${CXX} $lame_header -c tmp.c -o tmp 2>&3
    then
        ${ECHO} "OK"
        msg_chkfor "link with libmp3lame (lame)"
        if ${CXX} $lame_header $lame_lib tmp.c -o tmp -lmp3lame 2>&3
        then
            ${ECHO} "OK"
            ${ECHO} "#_______________________" >&4
                ${ECHO} "WITH_LIBLAME:=1" >&4
                ${ECHO} "CXXFLAGS_LIBLAME:=" >&4
                ${ECHO} "CXXFLAGS+=$lame_header" >&4
                ${ECHO} "LDFLAGS+=$lame_lib" >&4
                [ "$STATIC" -eq 0 ] && ${ECHO} "LIBS_LIBLAME:=-lmp3lame" >&4
                ${ECHO} "SRC_LIBLAME:=lame_encode.cpp" >&4
                ${ECHO} "" >&4
                MP3=1
            else
                ${ECHO} "FAILED"
                ${ECHO} "WITH_LIBLAME:=0" >&4
            fi
        else
            ${ECHO} "FAILED"
            ${ECHO} "WITH_LIBLAME:=0" >&4
        fi
}

check_libvorbis() {

    cat << EOF >tmp.c
#include <vorbis/vorbisenc.h>
int main() {

vorbis_info vi;
vorbis_info_init(&vi);

return 0;
}
EOF
    msg_chkfor "compile with libvorbis"
    if ${CXX} $vorbis_header -c tmp.c -o tmp 2>&3
    then
        ${ECHO} "OK"
        msg_chkfor "link with libvorbis"
        if ${CXX} $vorbis_header $vorbis_lib tmp.c -o tmp -lvorbis -lvorbisenc 2>&3
        then
            ${ECHO} "OK"
            ${ECHO} "#_______________________" >&4
                ${ECHO} "WITH_LIBVORBIS:=1" >&4
                ${ECHO} "CXXFLAGS_LIBVORBIS:=" >&4
                ${ECHO} "CXXFLAGS+=$vorbis_header" >&4
                ${ECHO} "LDFLAGS+=$vorbis_lib" >&4
                [ "$STATIC" -eq 0 ] && ${ECHO} "LIBS_LIBVORBIS:=-lvorbisenc -lvorbis -logg" >&4
                ${ECHO} "SRC_LIBVORBIS:=vorbis_encode.cpp" >&4
                ${ECHO} "" >&4
                OGG=1
            else
                ${ECHO} "FAILED"
                ${ECHO} "WITH_LIBVORBIS:=0" >&4
            fi
        else
            ${ECHO} "FAILED"
            ${ECHO} "WITH_LIBVORBIS:=0" >&4
        fi
}

check_libopus() {

    cat << EOF > tmp.c
#include <opus/opus.h>
int main() {
  opus_get_version_string();
  return 0;
}
EOF
    msg_chkfor "compile with libopus"
    if ${CXX} -c tmp.c -o /dev/null 2>&3
    then
      ${ECHO} "OK"
      msg_chkfor "link with libopus"
      if ${CXX} tmp.c -o /dev/null -lopus 2>&3
      then
        ${ECHO} "OK"
        ${ECHO} "#_______________________" >&4
        ${ECHO} "WITH_LIBOPUS:=1" >&4
        ${ECHO} "CXXFLAGS_LIBOPUS:=" >&4
        ${ECHO} "CXXFLAGS+=$opus_header" >&4
        ${ECHO} "LDFLAGS+=$opus_lib" >&4
        [ "$STATIC" -eq 0 ] && ${ECHO} "LIBS_LIBOPUS:=-logg -lopus" >&4
        ${ECHO} "SRC_LIBOPUS:=opus_encode.cpp" >&4
        ${ECHO} "" >&4
        OPUS=1
      else
        ${ECHO} "FAILED"
        ${ECHO} "WITH_LIBOPUS:=0" >&4
      fi
    else
        ${ECHO} "FAILED"
        ${ECHO} "WITH_LIBOPUS:=0" >&4
    fi
}

#############################################################################


while [ $# -gt 0 ]
do
    case $1 in

    --help)
        cat <<EOF

    Options for configure:

    --prefix <prefix>       where to install
    --debug                 enable debug symbols

    --with(out)-mp3         build with mp3 support (default=yes)
    --with(out)-ogg         build with ogg support (default=yes)

    --pa-header <dir>       directory of portaudio v19 header
    --pa-lib <dir>          directory of portaudio v19 library
    --lame-header <dir>     directory of lame include folder
    --lame-lib <dir>        directory of libmp3lame 
    --vorbis-header <dir>   directory of vorbis include folder
    --vorbis-lib <dir>      directory of vorbis library

    --help                  shows usage of the configure script

EOF
            exit 0
            ;;

    --with-fltk) CHECK_FLTK=1;;
    --with-qt) CHECK_QT=1 CHECK_FLTK=0;;
    --with-ogg) CHECK_LIBVORBIS=1;;
    --without-ogg) CHECK_LIBVORBIS=0;;
    --with-opus) CHECK_LIBOPUS=1;;
    --without-opus) CHECK_LIBOPUS=0;;
    --with-mp3) CHECK_LIBLAME=1;;
    --without-mp3) CHECK_LIBLAME=0;;
    --static) STATIC=1;;

    --prefix)
        shift
        if [ $# -gt 0 ]
        then
            prefix=$1
        else
            ${ECHO} "error, missing argument for --prefix."
            exit 1
        fi
        ;;

    --pa-header)
        shift
        if [ $# -gt 0 ]
        then
            pa_header="-I$1"
        else
            ${ECHO} "error, missing argument for --pa-header."
            exit 1
        fi
        ;;

    --pa-lib)
        shift
        if [ $# -gt 0 ]
        then
            pa_lib="-L$1"
        else
            ${ECHO} "error, missing argument for --pa-lib."
            exit 1
        fi
        ;;

    --lame-header)
        shift
        if [ $# -gt 0 ]
        then
            lame_header="-I$1"
        else
            ${ECHO} "error, missing argument for --lame-header."
            exit 1
        fi
        ;;

    --lame-lib)
        shift
        if [ $# -gt 0 ]
        then
            lame_lib="-L$1"
        else
            ${ECHO} "error, missing argument for --lame-lib."
            exit 1
        fi
        ;;

    --vorbis-header)
        shift
        if [ $# -gt 0 ]
        then
            vorbis_header="-I$1"
        else
            ${ECHO} "error, missing argument for --vorbis-header."
            exit 1
        fi
        ;;

    --vorbis-lib)
        shift
        if [ $# -gt 0 ]
        then
            vorbis_lib="-L$1"
        else
            ${ECHO} "error, missing argument for --vorbis-lib."
            exit 1
        fi
        ;;

    --opus-lib)
        shift
        if [ $# -gt 0 ]
        then
            opus_lib="-L$1"
        else
            ${ECHO} "error, missing argument for --opus-lib."
            exit 1;
        fi
        ;;

    --debug)
        CXXFLAGS="${CXXFLAGS} -g"
        LDFLAGS="${LDFLAGS} -g"
        ;;

        *)
            ${ECHO} "error, invalid argument: $1"
            exit 1
        ;;
    esac
    shift
done


##############################################################

exec 3> config.log
exec 4> config.mk

${ECHO} "# butts's config.mk" >&4
${ECHO} "#_______________________" >&4
${ECHO} "DIST_VER=butt-0.1.12" >&4
${ECHO} "VERSION=\\\"butt-0.1.12\\\"" >&4
${ECHO} "prefix=$prefix" >&4
${ECHO} "CXX=${CXX}" >&4
${ECHO} "CXXFLAGS=${CXXFLAGS}" >&4
${ECHO} "LDFLAGS=${LDFLAGS}" >&4
${ECHO} "LIBS=${LIBS}" >&4
${ECHO} "#_______________________" >&4
${ECHO} "" >&4


if [ "$CHECK_FLTK" -eq 1 ] && [ "$CHECK_QT" -eq 1 ]
then
    ${ECHO} "you can't compile with FLTK and QT at the same time"
    exit 1
fi

if [ "$CHECK_FLTK" -eq 0 ] && [ "$CHECK_QT" -eq 0 ]
then
    ${ECHO} "you need to run configure with either --with-fltk or --with-qt"
    exit 1
fi

${ECHO} ""
#check_docs
check_tools
check_portaudio

[ "$CHECK_FLTK" -eq 1 ] && check_fltk
[ "$CHECK_QT" -eq 1 ] && check_qt
[ "$CHECK_LIBVORBIS" -eq 1 ] && check_libvorbis
[ "$CHECK_LIBOPUS" -eq 1 ] && check_libopus
[ "$CHECK_LIBLAME" -eq 1 ] && check_libmp3lame
[ "$STATIC" -eq 1 ] && ${ECHO} "LDFLAGS += -lpthread /usr/local/universal/lib/libportaudio.a /usr/local/universal/lib/libshout.a /usr/local/universal/lib/libvorbisenc.a /usr/local/universal/lib/libvorbis.a /usr/local/universal/lib/libogg.a /usr/local/universal/lib/libtheora.a /usr/local/universal/lib/libspeex.a /usr/local/universal/lib/libmp3lame.a -framework CoreAudio -framework AudioToolbox -framework AudioUnit -framework CoreServices" >&4
[ "$STATIC" -eq 0 ] && ${ECHO} "LDFLAGS += -lmp3lame" >&4


${ECHO} ""
${ECHO} "configure summary"
${ECHO} ""
#${ECHO} "GUI:              $GUI"

if [ "$OGG" -eq 1 ]
then
    ${ECHO} "ogg support:      YES"
else
    ${ECHO} "ogg support:      NO"
fi

if [ "$OPUS" -eq 1 ]
then
    ${ECHO} "opus support:     YES"
else
    ${ECHO} "opus support:     NO"
fi

if [ "$MP3" -eq 1 ]
then
    ${ECHO} "mp3 support:      YES"
else
    ${ECHO} "mp3 support:      NO"
fi

${ECHO} ""
${ECHO} "You may run \"make\" now"
${ECHO} "#_______________________" >&4
${ECHO} ""
${ECHO} "" >&4

rm -f tmp*

true

# vim:ft=sh
